SG-19789 licensing
shotgunsoftware/python-api pull request #236
Opened 2020-11-12 10:01 UTC by pscadding

This pr adds the licence information to a new software credits file.

I also found that the `xmlrpclib` packaged module did not appear to be used anymore. We were importing it through six instead. I've removed the module and the tests all appear fine. @jfboismenu do you have any concerns about this or know of anything I might have not thought of?

2020-11-12 13:12 UTC, jfboismenu approved these changes
Looks good to me. Have you had a change to take a look at the failing test? Any chance we can fix it quickly?

2020-11-12 13:13 UTC, jfboismenu requested changes
I think we're missing a requirements.txt file here actually.

2020-11-13 13:56 UTC, pscadding commented
The requirements.txt was already added when I added certifi, it is in `shotgun_api3/lib/requirements.txt`

2020-11-17 14:30 UTC, jfboismenu approved these changes

2020-11-17 16:38 UTC, eshokrgozar approved these changes

2020-11-19 13:41 UTC, merged